version: 2.1
jobs:
  build-and-publish:
    docker:
      - image: cimg/openjdk:17.0.14
        user: root
    working_directory: ~/eventuate-examples-docker-images
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish multi-arch artifacts
          command: |
            ./gradlew publishEventuateArtifacts
            docker context create tls-env
            docker buildx create tls-env --use
            docker run --privileged --rm tonistiigi/binfmt --install arm64,arm
            ./deploy-multi-arch-artifacts.sh
workflows:
  version: 2
  build:
    jobs:
      - build-and-publish:
          context:
            - publish
