version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.14
        user: root
    working_directory: ~/eventuate-examples-docker-images
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish multi-arch artifacts
          command: |
            ./gradlew -P version=$(./target-tag.sh) publishEventuateArtifacts
            docker context create tls-env
            docker buildx create tls-env --use
            docker run --privileged --rm tonistiigi/binfmt --install arm64,arm
            ./deploy-multi-arch-artifacts.sh
